### ISSUE TITLE
Refactoring suggestions...

### ISSUE THREAD

**Issue by flutefreak7** [gretastudier/PropulsionCourse#1]
Instead of 

    choice == 'Mars' or choice == 'mars':

You could use...
    choice.lower() == 'mars':

That way you aren't repeating yourself.

An even better refactor would be to just store all the apahelion's in a dictionary so that you aren't use if...else to do repetitive logic.  You can also use break to bust out of the while loop on success rather than tracking a sentinel value.  So something like this:

    aps = {'mars': 228000000,
           'mercury': 57909050.0,
           'venus': 108900000.0,
           'jupiter': 817000000.0,
           'saturn': 1500000000.0,
           'uranus': 3006900000.0,
           'neptune': 4547800000.0}
    
    while True:
        choice = raw_input("Please enter planet you wish to travel to: ")
        
        if choice.lower() in aps:
            data.loc[0,'Planet'] = choice
            break
        else:
            print "Sorry that's not a planet!"

**Comment by gretastudier** [comment]
Thank you so much! I'm pretty new to coding so this helps a lot, I really appreciate it!
